/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Semana10;

/**
 *
 * @author chris
 */
public class ejer05 extends javax.swing.JFrame {

    /**
     * Creates new form ejer05
     */
    public ejer05() {        
        initComponents();        
        this.setSize(600, 400);
        cbo_operaciones.addItem("Sumar");
        cbo_operaciones.addItem("Resta");
        cbo_operaciones.addItem("Multiplicación");
        cbo_operaciones.addItem("División");
        //this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_a = new javax.swing.JLabel();
        lb_b = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        txt_b = new javax.swing.JTextField();
        btn_suma = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        lb_anuncio = new javax.swing.JLabel();
        lb_resp = new javax.swing.JLabel();
        cbo_operaciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_a.setText("A:");
        getContentPane().add(lb_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lb_b.setText("B:");
        getContentPane().add(lb_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(txt_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 190, -1));
        getContentPane().add(txt_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 190, -1));

        btn_suma.setText("Ejecutar");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        lb_anuncio.setText("El resultado de la operación es: ");
        getContentPane().add(lb_anuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lb_resp.setText("0.0");
        getContentPane().add(lb_resp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        getContentPane().add(cbo_operaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // TODO add your handling code here:        
        float a,b, resp=0;
        a=Float.parseFloat(txt_a.getText());
        b=Float.parseFloat(txt_b.getText());
        String ope=cbo_operaciones.getSelectedItem().toString();
        if(ope.equals("Sumar"))resp=a+b;
        if(ope.equals("Resta"))resp=a-b;
        if(ope.equals("Multiplicación"))resp=a*b;
        if(ope.equals("División"))resp=a/b;
        this.lb_resp.setText(resp+"");
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        this.txt_a.setText("");
        this.txt_b.setText("");
        this.lb_resp.setText("0.0");
        this.txt_a.requestFocus();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejer05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejer05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejer05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejer05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejer05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_suma;
    private javax.swing.JComboBox<String> cbo_operaciones;
    private javax.swing.JLabel lb_a;
    private javax.swing.JLabel lb_anuncio;
    private javax.swing.JLabel lb_b;
    private javax.swing.JLabel lb_resp;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    // End of variables declaration//GEN-END:variables
}
