/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Semana10;

import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class ejer07 extends javax.swing.JFrame {

    /**
     * Creates new form ejer07
     */
    public ejer07() {
        initComponents();
        btng_grupo.add(rbtn_masculino);
        btng_grupo.add(rbtn_femenino);
        this.resize(500, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        btng_grupo = new javax.swing.ButtonGroup();
        rbtn_masculino = new javax.swing.JRadioButton();
        rbtn_femenino = new javax.swing.JRadioButton();
        btn_seleccion = new javax.swing.JButton();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtn_masculino.setText("Masculino");
        getContentPane().add(rbtn_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 59, -1, -1));

        rbtn_femenino.setText("Femenino");
        getContentPane().add(rbtn_femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 59, -1, -1));

        btn_seleccion.setText("Selecciono");
        btn_seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionActionPerformed
        // TODO add your handling code here:
        if(rbtn_femenino.isSelected()){
            JOptionPane.showMessageDialog(null, "Femenino");
        }else if(rbtn_masculino.isSelected()){
            JOptionPane.showMessageDialog(null, "Masculino");
        }else{
                JOptionPane.showMessageDialog(null, "No se selecciono");
                }
        
    }//GEN-LAST:event_btn_seleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejer07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejer07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejer07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejer07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejer07().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_seleccion;
    private javax.swing.ButtonGroup btng_grupo;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton rbtn_femenino;
    private javax.swing.JRadioButton rbtn_masculino;
    // End of variables declaration//GEN-END:variables
}
